# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('InstitutionCategory', models.CharField(blank=True, choices=[(b'Coaching', b'Coaching'), (b'School', b'School'), (b'College', b'College')], max_length=100, null=True)),
                ('InstitutionType', models.CharField(blank=True, max_length=100, null=True)),
                ('school_board', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.CharField(blank=True, max_length=6, null=True)),
                ('contact_details', models.BigIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('person_to_contact', models.CharField(blank=True, max_length=350, null=True)),
                ('full_address', models.CharField(blank=True, max_length=300, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_image_uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_Date', models.DateField(auto_now_add=True, null=True)),
                ('asked_Time', models.TimeField(auto_now_add=True, null=True)),
                ('Asked_Question', models.TextField(blank=True, null=True)),
                ('answer_is', models.TextField(blank=True, null=True)),
                ('is_answered_YesNo', models.BooleanField(default=False)),
                ('answer_on_date', models.DateField(blank=True, null=True)),
                ('answer_on_time', models.TimeField(blank=True, null=True)),
                ('is_edited_YesNo', models.BooleanField(default=False)),
                ('edited_on_date', models.DateField(blank=True, null=True)),
                ('edited_on_time', models.TimeField(blank=True, null=True)),
                ('number_of_likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('number_of_comments', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modifiedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_DateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_Content', models.TextField(blank=True, null=True)),
                ('comment_date', models.DateField(blank=True, null=True)),
                ('comment_time', models.TimeField(blank=True, null=True)),
                ('Question_is', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.AskQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_Content', models.TextField(blank=True, null=True)),
                ('comment_date', models.DateField(blank=True, null=True)),
                ('comment_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modifiedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_DateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'profile_image')),
                ('uploaded_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Help_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'profile_image')),
                ('uploaded_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('InstitutionName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.AboutInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(blank=True, choices=[(b'Topics', b'Topics'), (b'Comment', b'Comment'), (b'Answer', b'Answer')], max_length=200, null=True)),
                ('liked_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_image_uploaded', models.BooleanField(default=False)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('full_address', models.CharField(blank=True, max_length=300, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('isProfileComplete', models.BooleanField(default=False)),
                ('is_activeYesNO', models.BooleanField(default=False)),
                ('is_loggedIn', models.BooleanField(default=False)),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('Number_of_reviews', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.CityMaster')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.CountryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ResultCategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('addedDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAboutInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(blank=True, max_length=650, null=True)),
                ('review', models.CharField(blank=True, max_length=650, null=True)),
                ('addedDateTime', models.DateField(blank=True, null=True)),
                ('InstitutionName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.AboutInstitution')),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialisationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedOn', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modifiedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_DateTime', models.DateTimeField(blank=True, null=True)),
                ('countryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.CountryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='statistical_data_institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_year', models.DateField(blank=True, null=True)),
                ('no_of_student_admitted', models.BigIntegerField(blank=True, null=True)),
                ('no_of_student_succed', models.BigIntegerField(blank=True, null=True)),
                ('InstitutionName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.AboutInstitution')),
                ('result_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.ResultCategoryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TopicMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('addedDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YourArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('article_is', models.TextField(blank=True, null=True)),
                ('article_about', models.CharField(blank=True, max_length=300, null=True)),
                ('article_date', models.DateField(blank=True, null=True)),
                ('article_time', models.TimeField(blank=True, null=True)),
                ('number_of_likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('number_of_comments', models.BigIntegerField(blank=True, default=0, null=True)),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='specialisationmaster',
            name='areaOfSpecialisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.TopicMaster'),
        ),
        migrations.AddField(
            model_name='specialisationmaster',
            name='userIs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.StateMaster'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='likes',
            name='likes_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.AskQuestion'),
        ),
        migrations.AddField(
            model_name='likes',
            name='object_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.TopicMaster'),
        ),
        migrations.AddField(
            model_name='institutionimage',
            name='userId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='document',
            name='userId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='Article_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.YourArticle'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='comment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='stateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.StateMaster'),
        ),
        migrations.AddField(
            model_name='askquestion',
            name='Ask_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.TopicMaster'),
        ),
        migrations.AddField(
            model_name='askquestion',
            name='Asked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_to', to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='askquestion',
            name='userAsked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='aboutinstitution',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.MyUser'),
        ),
        migrations.AddField(
            model_name='aboutinstitution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.CityMaster'),
        ),
        migrations.AddField(
            model_name='aboutinstitution',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.CountryMaster'),
        ),
        migrations.AddField(
            model_name='aboutinstitution',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coachingApp.StateMaster'),
        ),
    ]
